services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks:
      - nextcloudnet
    deploy:
      resources:
        limits:
          cpus: "1.20"
          memory: 2048M
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - TZ=Europe/Berlin
    volumes:
      - ./persistence/nextcloud:/var/www/html
    restart: unless-stopped
    depends_on:
      - db
      - redis
    secrets:
      - db_password
      - db_username
      - db_name

  db:
    image: postgres:latest
    container_name: nextcloud_db
    networks:
      - nextcloudnet    
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1024M   
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_username
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - PGDATA=/var/lib/postgres/data/pgdata
      - TZ=Europe/Berlin
    volumes:
      - ./persistence/config_db:/var/lib/postgres/data
    restart: unless-stopped
    secrets:
      - db_password
      - db_username
      - db_name

  redis:
      image: redis:alpine
      container_name: redis-dbcache
      networks:
        - nextcloudnet
      restart: unless-stopped

  ingress:
    image: nginx:stable-alpine
    container_name: ingress
    networks:
      - nextcloudnet
    ports:
      - '9443:9443'
    restart: unless-stopped
    volumes:
      - ./persistence/nginx/conf.d:/etc/nginx/conf.d
      - ./persistence/nginx/ssl:/etc/nginx/ssl
      - ./persistence/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./persistence/nginx/public:/opt/test-static/public
      - ./persistence/nginx/downloads:/opt/downloads

networks:
  nextcloudnet:

secrets:
  db_password:
    file: ./db_password.txt
  db_username:
    file: ./db_username.txt
  db_name:
    file: ./db_name.txt
