events {}

http {
    server {
        listen 9443 ssl default_server;
        server_name 192.168.178.1;

        include conf.d/self-signed.conf;
        include conf.d/ssl-params.conf;

        error_page 497 https://$host:$server_port$request_uri;

        proxy_connect_timeout 60s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;

        # # set max upload size
        client_max_body_size 512M;
        fastcgi_buffers 64 4K;

        location = /.well-known/carddav {
            return 301 /remote.php/dav/;
        }

        location = /.well-known/caldav {
            return 301 /remote.php/dav/;
        }

        location / {
            proxy_pass http://nextcloud:80;

            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
        }
    }
}
